version: '3.8'

services:
  backend:
    build: ./BackEnd
    ports:
      - "3000:3000"
    volumes:
      - ./BackEnd:/app-backend
    networks:
      - mynetwork

  frontend:
    build: ./FrontEnd
    ports:
      - "8000:8000"
    volumes:
      - ./FrontEnd:/app-frontend
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/challenge2023.ddns.net/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/challenge2023.ddns.net/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - frontend
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork

